places = [
    "lawn",
    "patio",
    "vegetable garden",
    "deck",
    "swingset",
    "greenhouse",
    "barbecue pit",
    "bird bath",
    "pond",
    "herb garden",
    "formal garden",
    "horse stable",
    "trash heap",
    "compost pile",
    "area over the septic tank",
    "crawlspace",
    "dog door",
    "fire ring",
    "sandbox",
    "chicken coop",
    "doghouse",
    "rain barrel",
    "hornet's nest",
    "skunk den",
    "raccoon trap"
]